# @name create
POST {{host}}/Rounds
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "PlayerId": "",
    "CourseId": ""
}

### get based on location header
GET {{create.response.headers.Location}}
