# @name create
POST {{host}}/Rounds
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "PlayerId": "7f7783bd-0232-4be3-b6cf-c280f4445915",
    "CourseId": "384aaf4a-1a58-48ea-b29e-0dbc5aea0b44"
}

### get based on location header
GET {{create.response.headers.Location}}
