POST {{host}}/Import
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="Ollerup.csv"
Content-Type: text/csv

< ./Ollerup.csv
--boundary
Content-Disposition: form-data; name="age"

25
--boundary
Content-Disposition: form-data; name="gender"

Male
--boundary--