# @name create
POST {{host}}/Courses
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Name": "Bolbro Disc Golf Bane",
    "NumberOfHoles": 18,
    "Difficulty": "Moderate"
}

### get based on location header
GET {{create.response.headers.Location}}
