# @name create
POST {{host}}/Holes
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "HoleNumber": 2,
    "CourseId": "",
    "Par": 3
}

### get based on location header
GET {{create.response.headers.Location}}
