# @name create
POST {{host}}/Scores
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "RoundId": "",
    "HoleNumber": 1,
    "CourseId": "",
    "Strokes": 1
}

### get based on location header
GET {{create.response.headers.Location}}
